clear
close all
clc

%% Data Creation

% Time Vector
Step = 0.2;
T = 0:Step:4*pi;

% Signal Creation
Y1 = sin(T);
Y2 = cos(T);

%% Plotting
% plot(T, Y1, 'LineWidth', 3, 'LineStyle', ':', 'Color', 'k')
plot(T, Y1, ':ok', 'LineWidth', 3, 'DisplayName', '$\sin(t)$')
hold on
plot(T, Y2, ...
    'LineWidth', 3, ...
    'Marker', 's', ...
    'Color', 'r', ...
    'MarkerFaceColor', 'r', ...
    'MarkerSize', 8, ...
    'MarkerEdgeColor', 'r', ...
    'DisplayName', '$\frac{d}{dt}\sin(t)$')

xticks([0, 1, 2, 3, 4] * pi)
xticklabels(["0", "\pi", "2\pi", "3\pi", "4\pi"])

title('sin(t) / cos(t)', ...
    'FontSize', 20, ...
    'FontName', 'Times', ...
    'FontWeight', 'bold', ...
    'Color', [0, 0, 0])

xlabel('t [sec]', ...
    'FontSize', 15, ...
    'FontName', 'Times', ...
    'FontWeight', 'bold', ...
    'Color', 'k')
ylabel('Amplitude', ...
    'FontSize', 15, ...
    'FontName', 'Times', ...
    'FontWeight', 'bold', ...
    'Color', '#000000')

grid on
grid minor
% grid off

legend('FontSize', 25, ...
    'Interpreter', 'latex', ...
    'Location', 'ne')

% xlim([0, 4*pi])
% ylim([-1.1, 1.1])
% axis([0, 4*pi, -1.1, 1.1])
axis equal
axis([0, 4*pi, -1.1, 1.1])
% axis off